services:
  coruja-web:
    container_name: coruja-web-app    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Mapeia a porta 3009 do host para a porta 3009 do contêiner
      - "3009:3009"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - radares-net
networks:
  radares-net:
    external: true
      