version: '3.8'

services:
  coruja-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coruja-web-app
    restart: unless-stopped
    ports:
      # Mapeia a porta 3009 do host para a porta 3009 do contêiner
      - "3009:3009"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production